# Generated by Django 2.1.7 on 2019-03-20 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
